version: 2.1.0
url: https://qutang.github.io/cutie/
logo: /images/theme-icon.svg
slogan: Bazinga, theme cutie!

global:
  comment_system: valine # disqus, valine, gitment
  scheme: 
    name: Taurus #Taurus
    color: lime
  icon_set: blue-shadow
  use_animation: true

page_404:
  tencent_404: false

post:
  allow_share: true
  allow_modification: false
  allow_commercial: false
  use_lightgallery: true
  allow_comment: true
  toc_level: 2
  enable_unread_badge: false

changelog:
  v2.1.0:
    - Add Thumb Up functionality. Refer to <a href='https://github.com/qutang/hexo-theme-cutie/issues/89' target='_blank'>#89</a>.
  v2.0.17:
    - Remove unused scheme (Close <a href='https://github.com/qutang/hexo-theme-cutie/issues/81' target='_blank'>#81</a>)
    - Remove check new version functionality (not reliable)
    - Adjust header appearance
    - Adjust mobile view Refer to <a href='https://github.com/qutang/hexo-theme-cutie/issues/61' target='_blank'>#61</a>.
  v2.0.16:
    - Use jdenticon when post icon is unavailable.
  v2.0.15:
    - Bug fix of searching result links. Refer to <a href='https://github.com/qutang/hexo-theme-cutie/issues/85' target='_blank'>#85</a>.
  v2.0.14:
    - Bug fix during indexing search content. Refer to <a href='https://github.com/qutang/hexo-theme-cutie/issues/84' target='_blank'>#84</a>.
  v2.0.13:
    - Bug fix when displaying month name in the archive page <a href='https://github.com/qutang/hexo-theme-cutie/issues/66' target='_blank'>#66</a>. Thanks to <a href='https://github.com/imjdl' target='_blank'>@imjdl</a>.
  v2.0.12:
    - Linkify meta icons on cards
    - Minor appearance tweak
    - Fix a bug in displaying unread badge
  v2.0.11:
    - Better support for post excerpt
    - Support <a href='http://livere.com' target='_blank'>livere</a> comment system
  v2.0.10:
    - Import bug fix when parsing theme configuration (recommend to update)
    - Polish search page
    - Add Italian translation (contributed by <a href='https://github.com/Fastbyte01' target='_blank'>@fastbyte01</a>)
  v2.0.9:
    - Change primary font to Segoe UI
    - Optimize animation
    - Adjust appearance
    - Bug fix
  v2.0.8:
    - Bug fixes
    - Announcement will only be shown when visitor first sees it
    - Automate unread badge and post version management. No need to manually update <code>version</code> variable, set variable <code>enable_unread_badge</code> to <code>true</code> or <code>false</code> instead.
    - Optimize post visit and comment counts (reduce network requests)
  v2.0.7:
    - Auto hide/show of header and fotter during scrolling
    - Redesign of announcement, supporting both post annoucement and site announcement
    - No need to add search page yourself
    - No need to add 404 page yourself
    - Add support to use tencent 404 charity page
    - Change search from Google to in-site search
  v2.0.6-beta:
    - Bug fixes
  v2.0.5-beta:
    - Support animation
    - Support post copyright
    - Support light gallery zooming
    - Support post comment and visit counting
    - Support light gallery for all images in a post
    - Group posts by month adaptively in archive page

required_libs:
  js: https://cdn.jsdelivr.net/combine/npm/headroom.js@0.9.4,npm/jquery@3.3.1,npm/js-cookie@2.2.0,npm/jshashes@1.0.7/hashes.min.js,npm/loadjs@3.5.4/dist/loadjs.min.js,npm/swiper@4.3.5
  css: https://cdn.jsdelivr.net/combine/npm/animate.css@3.7.0,npm/swiper@4.3.5/dist/css/swiper.min.css

libs:
  anime:
    name: anime.js javascript animation library
    url: http://animejs.com/
    js: https://cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.min.js
  noty:
    name: noty.js notification library
    url: https://ned.im/noty/
    js: https://cdn.jsdelivr.net/npm/noty@3.2.0-beta/lib/noty.min.js
    css: https://cdn.jsdelivr.net/npm/noty@3.2.0-beta/lib/noty.min.css
  headroom:
    name: headroom.js
    url: http://wicky.nillia.ms/headroom.js/
  lightgallery:
    name: lightgallery.js
    url: https://sachinchoolur.github.io/lightgallery.js/
  jquery:
    name: jQuery library
    url: https://jquery.com/
  gitment:
    name: gitment comment system
    url: https://github.com/imsun/gitment
  valine:
    name: valine comment system
    url: https://valine.js.org/
    js: //unpkg.com/valine/dist/Valine.min.js
  leancloud:
    name: leancloud BAAS
    url: https://leancloud.cn/
    js: //cdn1.lncld.net/static/js/3.6.4/av-min.js
  mathjax:
    name: mathjax library
    url: https://www.mathjax.org/
  jscookie:
    name: "js-cookie.js: A javascript cookie manipulation library"
    url: https://github.com/js-cookie/js-cookie
    js: https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.0/js.cookie.min.js
  fontawesome:
    name: fontawesome
    url: https://fontawesome.com/
    js_cdn: https://use.fontawesome.com/releases/v5.0.6/js/all.js
    css: https://use.fontawesome.com/releases/v5.2.0/css/all.css
  fuse:
    name: "fuse.js: A javascript fuzzy search library"
    url: http://fusejs.io/
  jshashes:
    name: "hashes.js: A javascript hashing library"
    url: https://github.com/h2non/jshashes
    js: https://cdnjs.cloudflare.com/ajax/libs/jshashes/1.0.7/hashes.min.js
  loadjs:
    name: "loadjs.js: A javascript dependency management library"
    url: https://github.com/muicss/loadjs
    js: https://cdnjs.cloudflare.com/ajax/libs/loadjs/3.5.4/loadjs.min.js
  animate.css:
    name: "animate.css: A CSS framework for predefined animations"
    url: https://github.com/daneden/animate.css
  striptags:
    name: striptags
    url: https://www.npmjs.com/package/striptags
    js: /libs/striptags/src/striptags.js
  jdenticon:
    name: "Jdenticon: Open source library for generating identicons"
    url: https://jdenticon.com
    js_min: /libs/jdenticon/dist/jdenticon.min.js
    js: /libs/jdenticon/dist/jdenicon.js
  
  
  