version: 2.0.7
url: https://qutang.github.io/cutie/
logo: /images/theme-icon.svg
slogan: Bazinga, theme cutie!
# Configure navigation menu, provide a relative link and a path to icon (icon should better be square)

# As long as the name matches the font awesome icon name, you can add even more social links
# As the tip: the social link can be a QRCODE link

global:
  comment_system: valine # disqus, valine, gitment
  scheme: Taurus
  icon_set: blue-line
  use_animation: true

page_404:
  tencent_404: false

post:
  allow_share: true
  allow_modification: false
  allow_commercial: false
  use_lightgallery: true
  allow_comment: true
  toc_level: 2

changelog:
  v2.0.7:
    - Auto hide/show of header and fotter during scrolling
    - Redesign of announcement, supporting both post annoucement and site announcement
    - No need to add search page yourself
    - No need to add 404 page yourself
    - Add support to use tencent 404 charity page
    - Change search from Google to in-site search
  v2.0.6-beta:
    - Bug fixes
  v2.0.5-beta:
    - Support animation
    - Support post copyright
    - Support light gallery zooming
    - Support post comment and visit counting
    - Support light gallery for all images in a post
    - Group posts by month adaptively in archive page

libs:
  noty:
    css: /libs/noty/lib/noty.css
    js_min: /libs/noty/lib/noty.min.js
    js: /libs/noty/lib/noty.js
  tippy:
    js: /libs/tippy.js/dist/tippy.all.js
    js_min: /libs/tippy.js/dist/tippy.all.min.js
  headroom:
    js: /libs/headroom.js/dist/headroom.js
    js_min: /libs/headroom.js/dist/headroom.min.js
  lightgallery:
    js: /libs/lightgallery.js/dist/js/lightgallery.js
    js_min: /libs/lightgallery.js/dist/js/lightgallery.min.js
    css: /libs/lightgallery.js/dist/css/lightgallery.css
    css_min: /libs/lightgallery.js/dist/css/lightgallery.min.css
  lgzoom:
    js: /libs/lg-zoom/dist/lg-zoom.js
    js_min: /libs/lg-zoom/dist/lg-zoom.min.js
  jquery:
    js: /libs/jquery/dist/jquery.js
    js_min: /libs/jquery/dist/jquery.min.js
  gitment:
    js: /libs/gitment/dist/gitment.browser.js
    js_min: /libs/gitment/dist/gitment.browser.js
    css: /libs/gitment/style/default.css
  valine:
    js_cdn: //unpkg.com/valine/dist/Valine.min.js
  leancloud:
    js_cdn: //cdn1.lncld.net/static/js/3.6.4/av-min.js
  mathjax:
    js_cdn: https://cdnjs.cloudflare.com/ajax//libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML
  jscookie:
    js_cdn: https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js
  fontawesome:
    js_cdn: https://use.fontawesome.com/releases/v5.0.6/js/all.js
  fuse:
    js_min: /libs/fuse.js/dist/fuse.min.js
    js: /libs/fuse.js/dist/fuse.js
  
  
  